name: Changelog check

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, labeled, unlabeled ]

jobs:
  Changelog-Entry-Check:
    name: Check Changelog Action
    runs-on: ubuntu-latest
    steps:
      - uses: tarides/changelog-check-action@v1
    # We don't push changelog entries
    # steps:
    #   - uses: tarides/changelog-check-action@v1
